version: '3.4'

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

services:
  php-fpm:
    container_name: lx1036-php-fpm
    build:
      context: ./php-fpm
    volumes:
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    networks:
      - backend


